---
- name: Configure managed nodes - Basic packages
  hosts: bastion
  become: true
  tasks:
    - name: Update and install basic tools
      ansible.builtin.apt:
        update_cache: true
        name:
          - git
          - net-tools
          - joe
          - mc
        state: present

- name: Install Zabbix Agent 2 (7.0 LTS)
  hosts: all
  become: true
  tasks:
    - name: Import tasks for Zabbix Agent 2 installation
      ansible.builtin.import_tasks: /opt/repo/install-zabbix-agent2.yml