---
- name: Install community.zabbix collection
  ansible.builtin.command:
    cmd: ansible-galaxy collection install community.zabbix --force
  changed_when: false

- name: Install Zabbix Agent 2 (7.0 LTS) via community role
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_version: "7.0"
    zabbix_agent2: true
    zabbix_agent_version: "7.0"
    zabbix_agent_server: "192.168.56.10"
    zabbix_agent_serveractive: "192.168.56.10"
    zabbix_agent_hostname: "{{ inventory_hostname }}"
    zabbix_agent_hostmetadata: "linux-bastion-ansible:env=lab:role=ansible-bastion:os=ubuntu"
    zabbix_agent_listenip: "0.0.0.0"
    zabbix_agent_listenport: 10050
    zabbix_agent_host_state: present
    zabbix_agent_enabled: true

- name: Ensure Zabbix Agent 2 service is enabled and restarted
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes
    state: restarted
    daemon_reload: yes